# Generated by Django 4.0.1 on 2022-05-03 19:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('packs', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Round',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(max_length=32)),
            ],
        ),
        migrations.AddField(
            model_name='pack',
            name='title',
            field=models.TextField(db_index=True, default='title', max_length=32, unique=True),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='Theme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(max_length=32)),
                ('round', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='themes', to='packs.round')),
            ],
        ),
        migrations.AddField(
            model_name='round',
            name='pack',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rounds', to='packs.pack'),
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(max_length=512)),
                ('answer', models.TextField(max_length=512)),
                ('price', models.IntegerField(default=100)),
                ('theme', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='packs.theme')),
            ],
        ),
    ]
