# Generated by Django 4.0.1 on 2022-10-31 09:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('packs', '0003_pack_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='pack',
            name='is_deprecated',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='pack',
            name='version',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='pack',
            name='author',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='packs', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='pack',
            name='title',
            field=models.TextField(db_index=True, max_length=32),
        ),
        migrations.AlterUniqueTogether(
            name='pack',
            unique_together={('title', 'version')},
        ),
        migrations.CreateModel(
            name='RoundInGame',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('not_played_questions_count', models.IntegerField(default=0)),
                ('next_round_in_game', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='packs.roundingame')),
                ('round', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rounds_in_game', to='packs.round')),
            ],
        ),
        migrations.CreateModel(
            name='QuestionInGame',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('NP', 'Not played'), ('IP', 'Is playing'), ('WA', 'Wrong answer'), ('CA', 'Correct answer')], default='NP', max_length=2)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions_in_game', to='packs.question')),
                ('round_in_game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions_in_game', to='packs.roundingame')),
            ],
        ),
    ]
