# Generated by Django 4.0.1 on 2022-10-31 09:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0002_remove_room_admin_remove_room_has_access_and_more'),
        ('players', '0002_player_is_verified_player_verification_uuid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='username',
            field=models.CharField(db_index=True, max_length=50, unique=True),
        ),
        migrations.CreateModel(
            name='PlayerInGame',
            fields=[
                ('player', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='player_in_room', serialize=False, to=settings.AUTH_USER_MODEL)),
                ('is_room_admin', models.BooleanField(default=False, verbose_name='room admin status')),
                ('is_presenter', models.BooleanField(default=False, verbose_name='room presenter status')),
                ('score', models.IntegerField(default=0)),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='players_in_room', to='rooms.room')),
            ],
        ),
    ]
