# Generated by Django 4.0.1 on 2022-11-27 23:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0003_room_document_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='document_id',
            field=models.CharField(default=None, max_length=50, null=True),
        ),
    ]
